/**
 * ShopSilo Hyperlocal Category Taxonomy & Metadata
 * Comprehensive bilingual (English & Hindi) category data with departments, icons, and keyword search
 */

export const CATEGORY_DEPARTMENTS = [
  { id: 'all', nameEn: 'All Categories', nameHi: 'सभी श्रेणियां', icon: '✨' },
  { id: 'staples', nameEn: 'Kirana & Staples', nameHi: 'किराना व अनाज', icon: '🌾' },
  { id: 'dairy', nameEn: 'Dairy, Bakery & Eggs', nameHi: 'डेयरी, बेकरी व अंडे', icon: '🥛' },
  { id: 'fresh', nameEn: 'Fresh Fruits & Veggies', nameHi: 'ताज़ी सब्जियां व फल', icon: '🥦' },
  { id: 'snacks', nameEn: 'Snacks & Beverages', nameHi: 'नमकीन, बिस्कुट व पेय', icon: '🍪' },
  { id: 'personal', nameEn: 'Personal & Baby Care', nameHi: 'पर्सनल व बेबी केयर', icon: '🧴' },
  { id: 'household', nameEn: 'Home & Puja Care', nameHi: 'सफाई व पूजा सामग्री', icon: '🪔' },
  { id: 'health', nameEn: 'Pharmacy & Health', nameHi: 'दवाएं व स्वास्थ्य', icon: '💊' },
  { id: 'lifestyle', nameEn: 'Fashion, Electronics & Tools', nameHi: 'कपड़े, मोबाइल व हार्डवेयर', icon: '⚡' },
];

export const ALL_CATEGORIES = [
  // Kirana & Staples
  {
    id: 'rice-grains',
    slug: 'rice-grains',
    department: 'staples',
    nameEn: 'Rice & Grains',
    nameHi: 'चावल एवं अनाज',
    descriptionEn: 'Basmati, Raw Rice, Wheat, Millets, Poha & Oats',
    descriptionHi: 'बासमती, अरवा, उसना, गेहूं, बाजरा, पोहा व ओट्स',
    icon: '🍚',
    color: '#f59e0b',
    keywords: ['rice', 'chawal', 'grain', 'wheat', 'gehu', 'poha', 'oats', 'millet', 'basmati', 'arwa', 'usna'],
  },
  {
    id: 'pulses-lentils',
    slug: 'pulses-lentils',
    department: 'staples',
    nameEn: 'Pulses & Lentils',
    nameHi: 'दालें एवं दलहन',
    descriptionEn: 'Toor Dal, Moong, Masoor, Chana, Rajma & Urad',
    descriptionHi: 'अरहर, मूंग, मसूर, चना, राजमा व उड़द दाल',
    icon: '🥣',
    color: '#eab308',
    keywords: ['dal', 'pulse', 'lentil', 'toor', 'arhar', 'moong', 'masoor', 'chana', 'rajma', 'urad', 'chole'],
  },
  {
    id: 'flour-atta',
    slug: 'flour-atta',
    department: 'staples',
    nameEn: 'Flour & Atta',
    nameHi: 'आटा, मैदा व बेसन',
    descriptionEn: 'Chakki Atta, Maida, Besan, Suji & Rice Flour',
    descriptionHi: 'चक्की आटा, मैदा, चना बेसन, सूजी व चावल का आटा',
    icon: '🥡',
    color: '#f97316',
    keywords: ['atta', 'flour', 'maida', 'besan', 'suji', 'rawa', 'sattu', 'gehu ka atta'],
  },
  {
    id: 'edible-oils',
    slug: 'edible-oils',
    department: 'staples',
    nameEn: 'Edible Oils & Ghee',
    nameHi: 'तेल एवं देसी घी',
    descriptionEn: 'Mustard Oil, Refined Oil, Desi Ghee & Vanaspati',
    descriptionHi: 'सरसों तेल, रिफाइंड तेल, शुद्ध देसी घी व वनस्पति',
    icon: '🫒',
    color: '#d97706',
    keywords: ['oil', 'tel', 'mustard oil', 'sarson', 'refined oil', 'ghee', 'desi ghee', 'dalda', 'soyabean oil'],
  },
  {
    id: 'spices-masala',
    slug: 'spices-masala',
    department: 'staples',
    nameEn: 'Spices & Masala',
    nameHi: 'मसाले व गरम मसाला',
    descriptionEn: 'Haldi, Mirch, Dhaniya, Whole Spices & Blended Masalas',
    descriptionHi: 'हल्दी, लाल मिर्च, धनिया, खड़े मसाले व मिक्स मसाला',
    icon: '🌶️',
    color: '#ef4444',
    keywords: ['masala', 'spice', 'haldi', 'mirchi', 'chilli', 'dhaniya', 'garam masala', 'jeera', 'hing', 'elaichi', 'laung'],
  },
  {
    id: 'sugar-salt',
    slug: 'sugar-salt',
    department: 'staples',
    nameEn: 'Sugar, Salt & Jaggery',
    nameHi: 'चीनी, नमक व गुड़',
    descriptionEn: 'Refined Sugar, Iodized Salt, Black Salt, Gur & Honey',
    descriptionHi: 'रिफाइंड चीनी, आयोडीन नमक, काला नमक, गुड़ व शुद्ध शहद',
    icon: '🧂',
    color: '#64748b',
    keywords: ['sugar', 'cheeni', 'shakkar', 'salt', 'namak', 'gur', 'jaggery', 'honey', 'shahad', 'rock salt', 'sendha namak'],
  },
  {
    id: 'packaged-foods',
    slug: 'packaged-foods',
    department: 'staples',
    nameEn: 'Ready Cook & Packaged',
    nameHi: 'रेडी टू कुक व नूडल्स',
    descriptionEn: 'Maggi, Pasta, Macaroni, Papad, Vermicelli & Soups',
    descriptionHi: 'मैगी, पास्ता, मैकरोनी, पापड़, सेवई व सूप',
    icon: '🍜',
    color: '#dc2626',
    keywords: ['maggi', 'noodles', 'pasta', 'macaroni', 'papad', 'soup', 'ready to cook', 'sevai', 'vermicelli'],
  },

  // Dairy, Bakery & Eggs
  {
    id: 'milk-curd',
    slug: 'milk-curd',
    department: 'dairy',
    nameEn: 'Milk, Curd & Chaas',
    nameHi: 'दूध, दही व छाछ',
    descriptionEn: 'Fresh Pouch Milk, Dahi, Chaas, Lassi & Flavoured Milk',
    descriptionHi: 'ताज़ा दूध, पैकेट दही, छाछ, लस्सी व फ्लेवर्ड मिल्क',
    icon: '🥛',
    color: '#0284c7',
    keywords: ['milk', 'doodh', 'curd', 'dahi', 'chaas', 'buttermilk', 'lassi', 'sudha', 'amul'],
  },
  {
    id: 'butter-cheese',
    slug: 'butter-cheese',
    department: 'dairy',
    nameEn: 'Butter, Paneer & Cheese',
    nameHi: 'मक्खन, पनीर व चीज़',
    descriptionEn: 'Fresh Paneer, Salted Butter, Cheese Slices & Cream',
    descriptionHi: 'ताज़ा पनीर, बटर, चीज़ क्यूब्स व फ्रेश क्रीम',
    icon: '🧀',
    color: '#eab308',
    keywords: ['butter', 'paneer', 'cheese', 'cream', 'malai', 'makhan', 'amul butter', 'cheese slice'],
  },
  {
    id: 'bread-bakery',
    slug: 'bread-bakery',
    department: 'dairy',
    nameEn: 'Bread, Buns & Bakery',
    nameHi: 'ब्रेड, पाव व बेकरी',
    descriptionEn: 'White Bread, Brown Bread, Pav, Buns, Rusk & Cakes',
    descriptionHi: 'व्हाइट ब्रेड, ब्राउन ब्रेड, पाव, बर्गर बन, टोस्ट व केक',
    icon: '🍞',
    color: '#b45309',
    keywords: ['bread', 'pav', 'bun', 'bakery', 'rusk', 'toast', 'cake', 'muffin', 'cream roll'],
  },
  {
    id: 'eggs',
    slug: 'eggs',
    department: 'dairy',
    nameEn: 'Eggs',
    nameHi: 'अंडे (देसी व पोल्ट्री)',
    descriptionEn: 'Fresh Farm Eggs, Brown Organic Eggs & Quail Eggs',
    descriptionHi: 'ताज़े फार्म अंडे, देसी अंडे व ट्रे अंडे',
    icon: '🥚',
    color: '#f59e0b',
    keywords: ['egg', 'eggs', 'anda', 'ande', 'farm egg', 'desi anda', 'egg tray'],
  },

  // Fresh Fruits & Veggies
  {
    id: 'fresh-vegetables',
    slug: 'fresh-vegetables',
    department: 'fresh',
    nameEn: 'Fresh Vegetables',
    nameHi: 'ताज़ी हरी सब्जियां',
    descriptionEn: 'Potato, Onion, Tomato, Green Vegetables & Leafy Greens',
    descriptionHi: 'आलू, प्याज, टमाटर, हरी सब्जियां, धनिया व हरी मिर्च',
    icon: '🥦',
    color: '#10b981',
    keywords: ['vegetable', 'sabji', 'aloo', 'potato', 'pyaz', 'onion', 'tamatar', 'tomato', 'palak', 'gobhi', 'mirchi'],
  },
  {
    id: 'fresh-fruits',
    slug: 'fresh-fruits',
    department: 'fresh',
    nameEn: 'Fresh Fruits',
    nameHi: 'ताज़े फल',
    descriptionEn: 'Apples, Bananas, Oranges, Seasonal & Tropical Fruits',
    descriptionHi: 'सेब, केला, संतरा, अनार, पपीता व मौसमी फल',
    icon: '🍎',
    color: '#f43f5e',
    keywords: ['fruit', 'fruits', 'fal', 'seb', 'apple', 'kela', 'banana', 'santra', 'orange', 'aam', 'mango', 'anar'],
  },
  {
    id: 'meat-seafood',
    slug: 'meat-seafood',
    department: 'fresh',
    nameEn: 'Meat, Chicken & Fish',
    nameHi: 'चिकन, मटन व मछली',
    descriptionEn: 'Fresh Cut Chicken, Mutton, Rohu Fish & Prawns',
    descriptionHi: 'ताज़ा चिकन, मटन, रोहू मछली व समुद्री भोजन',
    icon: '🍗',
    color: '#e11d48',
    keywords: ['meat', 'chicken', 'murga', 'mutton', 'gosht', 'fish', 'machli', 'prawn', 'seafood'],
  },

  // Snacks & Beverages
  {
    id: 'biscuits-cookies',
    slug: 'biscuits-cookies',
    department: 'snacks',
    nameEn: 'Biscuits & Cookies',
    nameHi: 'बिस्कुट, कुकीज व रस्क',
    descriptionEn: 'Glucose, Marie, Cream Biscuits, Cookies & Rusks',
    descriptionHi: 'पारले-जी, मैरी, क्रीम बिस्कुट, कुकीज व टोस्ट',
    icon: '🍪',
    color: '#d97706',
    keywords: ['biscuit', 'cookies', 'parle g', 'marie', 'oreo', 'good day', 'rusk', 'toast', 'cream biscuit'],
  },
  {
    id: 'chips-namkeen',
    slug: 'chips-namkeen',
    department: 'snacks',
    nameEn: 'Chips, Namkeen & Snacks',
    nameHi: 'चिप्स, नमकीन व भुजिया',
    descriptionEn: 'Lays, Kurkure, Bhujia, Mixture, Peanuts & Popcorn',
    descriptionHi: 'लेज, कुरकुरे, आलू भुजिया, मिक्सचर नमकीन व मूंगफली',
    icon: '🍟',
    color: '#eab308',
    keywords: ['chips', 'namkeen', 'bhujia', 'kurkure', 'lays', 'mixture', 'peanut', 'moong dal', 'haldiram', 'bikaji'],
  },
  {
    id: 'tea-coffee',
    slug: 'tea-coffee',
    department: 'snacks',
    nameEn: 'Tea, Coffee & Health Drinks',
    nameHi: 'चाय पत्ती, कॉफी व हॉर्लिक्स',
    descriptionEn: 'Loose Tea, CTC Tea Bags, Instant Coffee, Horlicks & Bournvita',
    descriptionHi: 'चाय पत्ती, ग्रीन टी, कॉफी पाउडर, हॉर्लिक्स व बोर्नविटा',
    icon: '☕',
    color: '#92400e',
    keywords: ['tea', 'chai', 'chai patti', 'coffee', 'nescafe', 'bru', 'horlicks', 'bournvita', 'boost', 'green tea'],
  },
  {
    id: 'soft-drinks-juices',
    slug: 'soft-drinks-juices',
    department: 'snacks',
    nameEn: 'Cold Drinks & Juices',
    nameHi: 'कोल्ड ड्रिंक्स, जूस व पानी',
    descriptionEn: 'Cold Drinks, Fruit Juices, Soda, Energy Drinks & Packaged Water',
    descriptionHi: 'कोल्ड ड्रिंक्स, फ्रूट जूस, सोडा, एनर्जी ड्रिंक व मिनरल वाटर',
    icon: '🥤',
    color: '#06b6d4',
    keywords: ['drink', 'cold drink', 'juice', 'soda', 'coke', 'pepsi', 'sprite', 'frooti', 'maaza', 'sting', 'water', 'kinley', 'bisleri'],
  },

  // Personal & Baby Care
  {
    id: 'soap-bath',
    slug: 'soap-bath',
    department: 'personal',
    nameEn: 'Soap, Body Wash & Bath',
    nameHi: 'साबुन, बॉडी वॉश व हैंडवॉश',
    descriptionEn: 'Bathing Soaps, Liquid Handwash, Shower Gels & Sanitizers',
    descriptionHi: 'नहाने का साबुन, लिक्विड हैंडवॉश, बॉडी वॉश व सैनिटाइजर',
    icon: '🧼',
    color: '#0d9488',
    keywords: ['soap', 'sabun', 'body wash', 'handwash', 'dettol', 'lifebuoy', 'lux', 'dove', 'pears', 'savlon'],
  },
  {
    id: 'hair-care',
    slug: 'hair-care',
    department: 'personal',
    nameEn: 'Shampoo & Hair Care',
    nameHi: 'शैम्पू व हेयर ऑयल',
    descriptionEn: 'Anti-Dandruff Shampoos, Hair Conditioners & Coconut Oils',
    descriptionHi: 'शैम्पू, कंडीशनर, नारियल तेल, सरसों तेल व हेयर जेल',
    icon: '🧴',
    color: '#6366f1',
    keywords: ['shampoo', 'hair oil', 'tel', 'conditioner', 'clinic plus', 'head and shoulders', 'parachute', 'vatika', 'dabur amla'],
  },
  {
    id: 'skin-care',
    slug: 'skin-care',
    department: 'personal',
    nameEn: 'Skin Care & Creams',
    nameHi: 'फेस वॉश, क्रीम व लोशन',
    descriptionEn: 'Face Washes, Fairness Creams, Cold Creams & Talcum Powders',
    descriptionHi: 'फेस वॉश, क्रीम, बॉडी लोशन, वैसलीन व टैल्कम पाउडर',
    icon: '✨',
    color: '#ec4899',
    keywords: ['cream', 'face wash', 'lotion', 'vaseline', 'fair and lovely', 'glow and lovely', 'pond', 'nivea', 'boroplus'],
  },
  {
    id: 'oral-care',
    slug: 'oral-care',
    department: 'personal',
    nameEn: 'Toothpaste & Oral Care',
    nameHi: 'टूथपेस्ट व ब्रश',
    descriptionEn: 'Toothpaste, Toothbrushes, Mouthwash & Tongue Cleaners',
    descriptionHi: 'टूथपेस्ट, टूथब्रश, माउथवॉश व जीभी',
    icon: '🪥',
    color: '#2563eb',
    keywords: ['paste', 'toothpaste', 'brush', 'toothbrush', 'colgate', 'pepsodent', 'close up', 'sensodyne', 'dabur red', 'mouthwash'],
  },
  {
    id: 'baby-care',
    slug: 'baby-care',
    department: 'personal',
    nameEn: 'Baby Care & Diapers',
    nameHi: 'बच्चों के डायपर व प्रोडक्ट्स',
    descriptionEn: 'Baby Diapers, Baby Wipes, Baby Soap, Lotion & Cerelac',
    descriptionHi: 'बेबी डायपर, वाइप्स, बेबी सोप, तेल व सेरेलक',
    icon: '👶',
    color: '#38bdf8',
    keywords: ['baby', 'diaper', 'pampers', 'mamy poko', 'huggies', 'wipes', 'cerelac', 'johnson baby', 'baby oil'],
  },

  // Household & Puja Care
  {
    id: 'laundry-care',
    slug: 'laundry-care',
    department: 'household',
    nameEn: 'Detergent & Laundry Care',
    nameHi: 'सर्फ, डिटर्जेंट व साबुन',
    descriptionEn: 'Washing Powder, Liquid Detergent, Fabric Whitener & Bars',
    descriptionHi: 'डिटर्जेंट पाउडर, लिक्विड सर्फ, नील व कपड़े धोने का साबुन',
    icon: '🧺',
    color: '#3b82f6',
    keywords: ['surf', 'detergent', 'washing powder', 'surf excel', 'tide', 'ariel', 'ghadi', 'rin', 'ujala', 'comfort'],
  },
  {
    id: 'home-cleaning',
    slug: 'home-cleaning',
    department: 'household',
    nameEn: 'Cleaners & Disinfectants',
    nameHi: 'हार्पिक, फिनाइल व डिशवॉश',
    descriptionEn: 'Floor Cleaners, Toilet Cleaners, Dishwash Liquid & Mosquito Repellents',
    descriptionHi: 'हार्पिक, फिनाइल, विम बार, लिक्विड डिशवॉश व मच्छर अगरबत्ती',
    icon: '🧽',
    color: '#14b8a6',
    keywords: ['harpic', 'lizol', 'phenyl', 'dishwash', 'vim', 'pril', 'good knight', 'all out', 'hit', 'mortein', 'broom', 'jharu'],
  },
  {
    id: 'puja-religious',
    slug: 'puja-religious',
    department: 'household',
    nameEn: 'Puja & Religious Items',
    nameHi: 'अगरबत्ती, धूप व पूजा सामग्री',
    descriptionEn: 'Incense Sticks, Dhoop, Camphor, Diya Oil, Roli & Cotton Wicks',
    descriptionHi: 'अगरबत्ती, धूपबत्ती, कपूर, पूजा तेल, रोली, चंदन व बाती',
    icon: '🪔',
    color: '#f59e0b',
    keywords: ['puja', 'agarbatti', 'dhoop', 'kapoor', 'camphor', 'diya', 'chandan', 'roli', 'moli', 'janeu', 'gangajal', 'matchbox', 'machis'],
  },
  {
    id: 'stationery-office',
    slug: 'stationery-office',
    department: 'household',
    nameEn: 'Stationery, Pens & Notebooks',
    nameHi: 'कॉपी, कलम व स्टेशनरी',
    descriptionEn: 'Ball Pens, Gel Pens, Notebooks, Registers, Tape & Glue',
    descriptionHi: 'पेन, पेंसिल, कॉपी, रजिस्टर, फेविकोल, स्टेपलर व फाइल',
    icon: '📚',
    color: '#4f46e5',
    keywords: ['pen', 'pencil', 'notebook', 'copy', 'register', 'fevicol', 'tape', 'glue', 'eraser', 'sharpener', 'stationery'],
  },

  // Pharmacy & Health
  {
    id: 'pharmacy',
    slug: 'pharmacy',
    department: 'health',
    nameEn: 'Daily Pharmacy & First Aid',
    nameHi: 'दवाएं, बाम व फर्स्ट एड',
    descriptionEn: 'Pain Relief Balms, Band-Aids, Antiseptic Liquids, ORS & Cough Syrups',
    descriptionHi: 'झंडू बाम, मूव, आयोडेक्स, हैंडीप्लास्ट, डेटॉल, ओआरएस व विक्स',
    icon: '💊',
    color: '#e11d48',
    keywords: ['pharmacy', 'medicine', 'dawa', 'tablet', 'paracetamol', 'balm', 'zandu balm', 'moov', 'iodex', 'vicks', 'bandaid', 'ors'],
  },
  {
    id: 'vitamins-supplements',
    slug: 'vitamins-supplements',
    department: 'health',
    nameEn: 'Chyawanprash & Nutrition',
    nameHi: 'च्यवनप्राश व न्यूट्रिशन',
    descriptionEn: 'Dabur Chyawanprash, Glucose Powder, Protein Powders & Honey',
    descriptionHi: 'डाबर च्यवनप्राश, ग्लूकोज पाउडर, प्रोटीन व इम्युनिटी बूस्टर',
    icon: '🍯',
    color: '#f59e0b',
    keywords: ['chyawanprash', 'dabur', 'glucose', 'glucon d', 'nutrition', 'vitamin', 'calcium', 'protein'],
  },

  // Fashion, Electronics & Tools
  {
    id: 'mobile-accessories',
    slug: 'mobile-accessories',
    department: 'lifestyle',
    nameEn: 'Mobile Accessories & Cables',
    nameHi: 'मोबाइल चार्जर, केबल व कवर',
    descriptionEn: 'Fast Chargers, Type-C Cables, Earphones, OTG & Power Banks',
    descriptionHi: 'फास्ट चार्जर, डेटा केबल, इयरफोन, हेडफोन व मोबाइल ग्लास',
    icon: '🔌',
    color: '#0284c7',
    keywords: ['mobile', 'charger', 'cable', 'type c', 'earphone', 'headphone', 'tempered glass', 'power bank', 'cover'],
  },
  {
    id: 'electronics',
    slug: 'electronics',
    department: 'lifestyle',
    nameEn: 'Small Electronics & Gadgets',
    nameHi: 'इलेक्ट्रॉनिक सामान व गैजेट्स',
    descriptionEn: 'Smartwatches, Bluetooth Speakers, Trimmers & Extension Boards',
    descriptionHi: 'स्मार्टवॉच, ब्लूटूथ स्पीकर, ट्रिमर, एक्सटेंशन बोर्ड व टॉर्च',
    icon: '⚡',
    color: '#f59e0b',
    keywords: ['electronics', 'speaker', 'bluetooth', 'trimmer', 'smartwatch', 'torch', 'extension board', 'battery'],
  },
  {
    id: 'hardware-electrical',
    slug: 'hardware-electrical',
    department: 'lifestyle',
    nameEn: 'Electricals, LED Bulbs & Tools',
    nameHi: 'LED बल्ब, तार व हार्डवेयर',
    descriptionEn: 'LED Bulbs, Tube Lights, Switches, PVC Tape, Nails & Tools',
    descriptionHi: 'LED बल्ब, ट्यूबलाइट, स्विच, टेप, पेचकस, हथौड़ी व हार्डवेयर',
    icon: '💡',
    color: '#ca8a04',
    keywords: ['bulb', 'led bulb', 'light', 'switch', 'wire', 'tape', 'hardware', 'screw', 'hammer', 'plug'],
  },
  {
    id: 'clothing-fashion',
    slug: 'clothing-fashion',
    department: 'lifestyle',
    nameEn: 'Clothing & Footwear',
    nameHi: 'कपड़े, होजरी व जूते-चप्पल',
    descriptionEn: 'T-Shirts, Jeans, Daily Wear, Innerwear, Socks & Slippers',
    descriptionHi: 'टी-शर्ट, शर्ट, गमछा, गंजी, अंडरवियर, मोजे व हवाई चप्पल',
    icon: '👕',
    color: '#7c3aed',
    keywords: ['clothing', 'cloth', 'kapda', 'tshirt', 'shirt', 'gamchha', 'underwear', 'slipper', 'chappal', 'shoes'],
  }
];

export const getCategoryMeta = (catOrId) => {
  if (!catOrId) return null;
  const idOrName = typeof catOrId === 'string' ? catOrId : (catOrId.id || catOrId.slug || catOrId.name || '');
  const lower = idOrName.toLowerCase().trim();

  // 1. Direct ID/slug match
  const direct = ALL_CATEGORIES.find(
    c => c.id.toLowerCase() === lower ||
         c.slug.toLowerCase() === lower ||
         c.nameEn.toLowerCase() === lower ||
         c.nameHi === idOrName
  );
  if (direct) return direct;

  // 2. Keyword fuzzy match
  for (const cat of ALL_CATEGORIES) {
    if (cat.keywords.some(k => lower.includes(k) || k.includes(lower))) {
      return cat;
    }
  }

  // 3. Fallback
  return {
    id: typeof catOrId === 'object' ? catOrId.id || catOrId.slug || 'custom' : catOrId,
    slug: typeof catOrId === 'object' ? catOrId.slug || catOrId.id || 'custom' : catOrId,
    nameEn: typeof catOrId === 'object' ? catOrId.name || catOrId.id : catOrId,
    nameHi: typeof catOrId === 'object' ? catOrId.name || catOrId.id : catOrId,
    descriptionEn: 'Neighborhood store category',
    descriptionHi: 'स्थानीय दुकान की श्रेणी',
    icon: '🏷️',
    color: '#6366f1',
    department: 'staples',
    keywords: [],
  };
};
